"""VK bot command text aliases → handler keys."""

COMMAND_ALIASES: dict[str, str] = {
    "начать": "welcome",
    "start": "welcome",
    "привет": "welcome",
    "здравствуйте": "welcome",
    "hello": "welcome",
    "меню": "welcome",
    "🏠 меню": "welcome",
    "главная": "welcome",
    "🏠 главная": "welcome",
    "📋 объявления": "classifieds",
    "объявления": "classifieds",
    "объявление": "classifieds",
    "доска": "classifieds",
    "🛠 услуги": "services",
    "услуги": "services",
    "мастера": "services",
    "огород": "services",
    "дрова": "services",
    "🔔 подписаться": "subscribe_all",
    "подписаться": "subscribe_all",
    "подписка": "subscribe_all",
    "подписка все": "subscribe_all",
    "подписка работа": "subscribe_jobs",
    "подписка вакансии": "subscribe_jobs",
    "🔔 работа": "subscribe_jobs",
    "подписка дрова": "subscribe_preset",
    "подписка услуги": "subscribe_preset",
    "подписка огород": "subscribe_preset",
    "подписка сосед": "subscribe_preset",
    "подписка neighbor": "subscribe_preset",
    "подписка garden": "subscribe_preset",
    "подписка firewood": "subscribe_preset",
    "🔕 отписаться": "unsubscribe",
    "отписаться": "unsubscribe",
    "🤖 ии-помощник": "ai_enter",
    "ии-помощник": "ai_enter",
    "ии": "ai_enter",
    "ai": "ai_enter",
    "помощник": "ai_enter",
    "💡 примеры вопросов": "ai_examples",
    "примеры": "ai_examples",
    "🎨 картинки на сайте": "ai_images",
    "картинки": "ai_images",
    "нарисуй": "ai_images",
    "🚪 выйти из ии": "ai_exit",
    "выйти из ии": "ai_exit",
    "стоп": "ai_exit",
    "💼 работа": "jobs",
    "работа": "jobs",
    "вакансии": "jobs",
    "вакансия": "jobs",
    "подработка": "jobs",
    "🛤 маршруты": "routes",
    "маршруты": "routes",
    "маршрут": "routes",
    "куда сходить": "routes",
    "экскурсия": "routes",
    "🗺 ошибка карты": "map_report",
    "ошибка карты": "map_report",
    "ошибка на карте": "map_report",
    "карта ошибка": "map_report",
    "➕ объявление": "classified_add",
    "подать объявление": "classified_add",
    "добавить объявление": "classified_add",
    "разместить объявление": "classified_add",
    "💡 пожелания": "wish",
    "пожелания": "wish",
    "предложения": "wish",
    "идея для сайта": "wish",
    "🚕 такси": "taxi",
    "такси": "taxi",
    "⚠️ жалобы": "complaints_info",
    "жалобы": "complaints_info",
    "обращения": "complaints_info",
    "жалоба": "complaints_info",
    "📝 регистрация": "register",
    "регистрация": "register",
    "зарегистрироваться": "register",
    "🌐 сайт": "site",
    "сайт": "site",
    "🗺 карта": "map",
    "карта": "map",
    "🌤 погода": "weather",
    "погода": "weather",
    "прогноз": "weather",
    "погода на завтра": "weather",
    "почасовая погода": "weather",
    "почасовой прогноз": "weather",
    "📋 мои обращения": "my_issues",
    "мои обращения": "my_issues",
    "статус обращения": "my_issues",
    "статус заявки": "my_issues",
    "🪶 кабинет": "cabinet",
    "кабинет": "cabinet",
    "личный кабинет": "cabinet",
    "мой кабинет": "cabinet",
    "📅 афиша": "events",
    "афиша": "events",
    "события": "events",
    "событие": "events",
    "кино": "events",
    "мероприятия": "events",
    "ℹ️ помощь": "help",
    "помощь": "help",
}
