#!/usr/bin/env python3
"""Generate stage-02 place inventory with structured sources[] (Yandex + 2GIS reconcile)."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

CHECKED = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
BASELINE_GIT = "2e48e1abbfc4b4284f88bef18d22817c8e56a5d8"

MAP_SUPPORTS = [
    "existence",
    "name",
    "category",
    "address",
    "coordinates",
    "phone",
    "opening_hours",
    "active_status",
]


def src(
    type_: str,
    url: str,
    *,
    entity_id: str | None = None,
    supports: list[str] | None = None,
) -> dict:
    return {
        "type": type_,
        "url": url,
        "entity_id": entity_id,
        "checked_at": CHECKED,
        "supports": supports or MAP_SUPPORTS.copy(),
    }


def gis(firm_id: str, supports: list[str] | None = None) -> dict:
    return src("TWO_GIS", f"https://2gis.ru/firm/{firm_id}", entity_id=firm_id, supports=supports)


def yandex_org(slug: str, entity_id: str, supports: list[str] | None = None) -> dict:
    return src(
        "YANDEX",
        f"https://yandex.ru/maps/org/{slug}/{entity_id}/",
        entity_id=entity_id,
        supports=supports,
    )


def yandex_search(query_url: str, supports: list[str] | None = None) -> dict:
    return src("YANDEX", query_url, entity_id=None, supports=supports)


def entry(
    stable_key: str,
    public_name: str,
    category: str,
    scope: str,
    address: str,
    lat: float,
    lng: float,
    *,
    aliases: list[str] | None = None,
    phone: str | None = None,
    opening_hours: str | None = None,
    website: str | None = None,
    social_url: str | None = None,
    yandex_url: str | None = None,
    yandex_id: str | None = None,
    osm_id: str | None = None,
    sources: list[dict] | None = None,
    existence_status: str = "YANDEX_ACTIVE",
    name_status: str = "YANDEX_ACTIVE",
    category_status: str = "YANDEX_ACTIVE",
    address_status: str = "YANDEX_ACTIVE",
    coordinates_status: str = "YANDEX_ACTIVE",
    phone_status: str = "UNVERIFIED",
    hours_status: str = "UNVERIFIED",
    active_status: str = "ACTIVE",
    decision: str = "RESTORE",
    decision_reason: str = "",
    verification_note: str | None = None,
    seed_as_reference: bool = True,
    conflict_notes: str | None = None,
) -> dict:
    return {
        "stable_key": stable_key,
        "public_name": public_name,
        "aliases": aliases or [],
        "category": category,
        "scope": scope,
        "address": address,
        "latitude": lat,
        "longitude": lng,
        "phone": phone,
        "opening_hours": opening_hours,
        "website": website,
        "social_url": social_url,
        "yandex_url": yandex_url,
        "yandex_id": yandex_id,
        "osm_id": osm_id,
        "sources": sources or [],
        "source_checked_at": CHECKED,
        "existence_status": existence_status,
        "name_status": name_status,
        "category_status": category_status,
        "address_status": address_status,
        "coordinates_status": coordinates_status,
        "phone_status": phone_status,
        "hours_status": hours_status,
        "active_status": active_status,
        "conflict_notes": conflict_notes,
        "decision": decision,
        "decision_reason": decision_reason,
        "verification_note": verification_note,
        "seed_as_reference": seed_as_reference,
    }


places: list[dict] = [
    entry(
        "shinomontazh-aerodromnaya-23",
        "Шиномонтаж",
        "tyre",
        "VILLAGE",
        "ул. Аэродромная, 23",
        57.0173,
        28.9335,
        aliases=["Шиномонтажная мастерская"],
        phone="+7 (906) 221-03-54",
        yandex_url="https://yandex.ru/maps/?text=%D1%88%D0%B8%D0%BD%D0%BE%D0%BC%D0%BE%D0%BD%D1%82%D0%B0%D0%B6%20%D0%90%D1%8D%D1%80%D0%BE%D0%B4%D1%80%D0%BE%D0%BC%D0%BD%D0%B0%D1%8F%2023%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%93%D0%BE%D1%80%D1%8B",
        sources=[
            src("OWNER", "owner:project", supports=["existence", "name", "address", "phone", "active_status"]),
            yandex_search(
                "https://yandex.ru/maps/?text=%D1%88%D0%B8%D0%BD%D0%BE%D0%BC%D0%BE%D0%BD%D1%82%D0%B0%D0%B6%20%D0%90%D1%8D%D1%80%D0%BE%D0%B4%D1%80%D0%BE%D0%BC%D0%BD%D0%B0%D1%8F%2023%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%93%D0%BE%D1%80%D1%8B",
                supports=["existence", "name", "category", "address", "coordinates", "active_status"],
            ),
            gis("70000001075370090", supports=["existence", "name", "category", "address", "phone", "active_status"]),
        ],
        existence_status="OWNER_CONFIRMED",
        name_status="OWNER_CONFIRMED",
        category_status="MULTISOURCE_CONFIRMED",
        address_status="OWNER_CONFIRMED",
        coordinates_status="MULTISOURCE_CONFIRMED",
        phone_status="OWNER_CONFIRMED",
        hours_status="UNVERIFIED",
        decision="RESTORE",
        decision_reason="OWNER_CONFIRMED; Yandex search card + 2GIS firm 70000001075370090",
    ),
    entry(
        "pyaterochka-lenina-20a",
        "Пятёрочка",
        "supermarket",
        "VILLAGE",
        "ул. Ленина, 20А",
        57.0264,
        28.9106,
        phone="8-800-555-55-05",
        opening_hours="ежедневно 08:00–23:00",
        website="https://5ka.ru",
        yandex_url="https://yandex.ru/maps/org/pyatyorochka/48515124540/",
        yandex_id="48515124540",
        sources=[
            yandex_org("pyatyorochka", "48515124540"),
            gis("70000001053567895"),
            src("CHAIN_STORE_LOCATOR", "https://5ka.ru", supports=["existence", "name"]),
        ],
        existence_status="MULTISOURCE_CONFIRMED",
        name_status="MULTISOURCE_CONFIRMED",
        category_status="MULTISOURCE_CONFIRMED",
        address_status="MULTISOURCE_CONFIRMED",
        coordinates_status="MULTISOURCE_CONFIRMED",
        phone_status="UNVERIFIED",
        hours_status="MULTISOURCE_CONFIRMED",
        decision="RESTORE",
        decision_reason="Yandex org + 2GIS firm + chain locator",
    ),
    entry(
        "pyaterochka-pushkinskaya-11",
        "Пятёрочка",
        "supermarket",
        "VILLAGE",
        "ул. Пушкинская, 11",
        57.0259,
        28.9148,
        phone="8-800-555-55-05",
        website="https://5ka.ru",
        yandex_url="https://yandex.ru/maps/org/pyatyorochka/48299237149/",
        yandex_id="48299237149",
        sources=[
            yandex_org("pyatyorochka", "48299237149"),
            src("CHAIN_STORE_LOCATOR", "https://5ka.ru", supports=["existence", "name"]),
        ],
        existence_status="YANDEX_ACTIVE",
        decision="RESTORE",
        decision_reason="Second Pyaterochka branch — separate address",
    ),
    entry(
        "magnit-lenina-42",
        "Магнит",
        "supermarket",
        "VILLAGE",
        "ул. Ленина, 42",
        57.0261,
        28.9112,
        phone="8-800-200-90-02",
        opening_hours="ежедневно до 22:00",
        website="https://magnit.ru",
        yandex_url="https://yandex.ru/maps/org/magnit/1613176821/",
        yandex_id="1613176821",
        sources=[
            yandex_org("magnit", "1613176821"),
            gis("70000001041826603"),
            src("CHAIN_STORE_LOCATOR", "https://magnit.ru", supports=["existence", "name"]),
        ],
        existence_status="MULTISOURCE_CONFIRMED",
        name_status="MULTISOURCE_CONFIRMED",
        category_status="MULTISOURCE_CONFIRMED",
        address_status="MULTISOURCE_CONFIRMED",
        coordinates_status="MULTISOURCE_CONFIRMED",
        hours_status="MULTISOURCE_CONFIRMED",
        decision="RESTORE",
        decision_reason="Yandex + 2GIS + Magnit chain",
    ),
    entry(
        "magnit-novorzhevskaya-25",
        "Магнит",
        "supermarket",
        "VILLAGE",
        "ул. Новоржевская, 25",
        57.0258,
        28.9125,
        phone="8-800-200-90-02",
        opening_hours="ежедневно до 21:00",
        website="https://magnit.ru",
        yandex_url="https://yandex.ru/maps/org/magnit/1624883377/",
        yandex_id="1624883377",
        sources=[
            yandex_org("magnit", "1624883377"),
            gis("70000001041826641"),
            src("CHAIN_STORE_LOCATOR", "https://magnit.ru", supports=["existence", "name"]),
        ],
        existence_status="MULTISOURCE_CONFIRMED",
        name_status="MULTISOURCE_CONFIRMED",
        category_status="MULTISOURCE_CONFIRMED",
        address_status="MULTISOURCE_CONFIRMED",
        coordinates_status="MULTISOURCE_CONFIRMED",
        hours_status="MULTISOURCE_CONFIRMED",
        decision="RESTORE",
        decision_reason="Separate Magnit branch Novorzhevskaya 25",
    ),
    entry(
        "m-kosmetik-lenina-42",
        "М.Косметик",
        "beauty",
        "VILLAGE",
        "ул. Ленина, 42",
        57.0261,
        28.9112,
        website="https://magnit.ru",
        yandex_url="https://yandex.ru/maps/org/magnit/1613176821/",
        yandex_id="1613176821",
        sources=[yandex_org("magnit", "1613176821", supports=["existence", "address", "coordinates"])],
        existence_status="YANDEX_ACTIVE",
        category_status="YANDEX_ACTIVE",
        decision="RESTORE",
        decision_reason="Cosmetics shop in Magnit building",
        verification_note="Магазин косметики в здании Магнит",
    ),
    entry(
        "apteka-a-lenina-20a",
        "Аптека-А",
        "pharmacy",
        "VILLAGE",
        "ул. Ленина, 20А",
        57.0263,
        28.9108,
        opening_hours="ежедневно 09:00–20:00",
        yandex_url="https://yandex.ru/maps/org/apteka_a/179577355749/",
        sources=[
            gis("70000001046944968"),
            yandex_org("apteka_a", "179577355749"),
        ],
        existence_status="MULTISOURCE_CONFIRMED",
        name_status="TWO_GIS_ACTIVE",
        category_status="TWO_GIS_ACTIVE",
        address_status="MULTISOURCE_CONFIRMED",
        coordinates_status="MULTISOURCE_CONFIRMED",
        hours_status="TWO_GIS_ACTIVE",
        phone_status="UNVERIFIED",
        decision="RESTORE",
        decision_reason="2GIS pharmacy card; same building as Pyaterochka per maps",
    ),
    entry(
        "apteka-a-novorzhevskaya-25",
        "Аптека-А",
        "pharmacy",
        "VILLAGE",
        "ул. Новоржевская, 25",
        57.0258,
        28.9125,
        phone="+7 (8112) 60-77-11",
        yandex_url="https://yandex.ru/maps/org/apteka_a/193128665660/",
        yandex_id="193128665660",
        sources=[yandex_org("apteka_a", "193128665660")],
        existence_status="YANDEX_ACTIVE",
        category_status="YANDEX_ACTIVE",
        phone_status="YANDEX_ACTIVE",
        decision="RESTORE",
        decision_reason="Dedicated Yandex pharmacy card at Novorzhevskaya 25",
    ),
    entry(
        "farm-m-lenina-42",
        "Фарм-М",
        "pharmacy",
        "VILLAGE",
        "ул. Ленина, 42",
        57.0261,
        28.9112,
        phone="+7 (960) 222-67-76",
        yandex_url="https://yandex.ru/maps/org/farm_m/158009837560/",
        yandex_id="158009837560",
        sources=[yandex_org("farm_m", "158009837560")],
        existence_status="YANDEX_ACTIVE",
        category_status="YANDEX_ACTIVE",
        phone_status="YANDEX_ACTIVE",
        decision="RESTORE",
        decision_reason="Third village pharmacy — active Yandex Maps card",
        verification_note="Same building as Magnit Lenina 42",
    ),
    entry(
        "vet-sbbzh-stroiteley-3",
        "Пушкиногорская станция по борьбе с болезнями животных",
        "vet",
        "VILLAGE",
        "ул. Строителей, 3",
        57.0298,
        28.9335,
        aliases=["Пушкиногорский филиал СББЖ"],
        yandex_url="https://yandex.ru/maps/org/pushkinogorskaya_stantsiya_po_borbe_s_boleznyami_zhivotnykh/151587943960/",
        yandex_id="151587943960",
        sources=[yandex_org("pushkinogorskaya_stantsiya_po_borbe_s_boleznyami_zhivotnykh", "151587943960")],
        existence_status="YANDEX_ACTIVE",
        category_status="YANDEX_ACTIVE",
        decision="RESTORE",
        decision_reason="Village veterinary clinic separate from human hospital",
        conflict_notes="2GIS also lists Stroiteley 3 filial and Sovkhozny 13 entry — Yandex card used as primary",
    ),
    entry(
        "raypo-trigorskaya-3",
        "Пушкиногорское РАЙПО",
        "supermarket",
        "VILLAGE",
        "ул. Тригорская, 3",
        57.0249,
        28.9048,
        phone="+7 (81146) 2-31-45",
        yandex_url="https://yandex.ru/maps/org/pushkinogorskoye_raypo/11910956685/",
        yandex_id="11910956685",
        sources=[yandex_org("pushkinogorskoye_raypo", "11910956685")],
        existence_status="YANDEX_ACTIVE",
        phone_status="YANDEX_ACTIVE",
        decision="RESTORE",
        decision_reason="Yandex active cooperative store",
        conflict_notes="Yandex hours show closed some days — not marked CLOSED without second source",
    ),
    entry(
        "svyatogor-cafe-lenina-2",
        "Святогоръ",
        "cafe",
        "VILLAGE",
        "ул. Ленина, 2",
        57.0265,
        28.9115,
        opening_hours="ежедневно 10:00–22:00",
        yandex_url="https://2gis.ru/firm/70000001030949997",
        sources=[gis("70000001030949997")],
        existence_status="TWO_GIS_ACTIVE",
        name_status="TWO_GIS_ACTIVE",
        category_status="TWO_GIS_ACTIVE",
        address_status="TWO_GIS_ACTIVE",
        hours_status="TWO_GIS_ACTIVE",
        phone_status="UNVERIFIED",
        decision="RESTORE",
        decision_reason="2GIS active cafe card Lenina 2",
    ),
    entry(
        "pushkin-park-lenina-42a",
        "Пушкин-Парк",
        "restaurant",
        "VILLAGE",
        "ул. Ленина, 42А",
        57.0262,
        28.9115,
        opening_hours="уточняйте перед визитом",
        yandex_url="https://2gis.ru/firm/70000001046501223",
        sources=[gis("70000001046501223")],
        existence_status="TWO_GIS_ACTIVE",
        name_status="TWO_GIS_ACTIVE",
        category_status="TWO_GIS_ACTIVE",
        address_status="TWO_GIS_ACTIVE",
        phone_status="UNVERIFIED",
        hours_status="TWO_GIS_ACTIVE",
        decision="RESTORE",
        decision_reason="2GIS restaurant card Lenina 42A",
    ),
    entry(
        "druzhba-hotel-lenina-8",
        "Дружба",
        "hotel",
        "VILLAGE",
        "ул. Ленина, 8",
        57.0263,
        28.9110,
        yandex_url="https://yandex.ru/maps/org/druzhba/1077179086/",
        yandex_id="1077179086",
        sources=[
            yandex_org("druzhba", "1077179086"),
            gis("70000001030945857"),
        ],
        existence_status="MULTISOURCE_CONFIRMED",
        name_status="MULTISOURCE_CONFIRMED",
        category_status="MULTISOURCE_CONFIRMED",
        address_status="MULTISOURCE_CONFIRMED",
        phone_status="UNVERIFIED",
        decision="RESTORE",
        decision_reason="Hotel — Yandex org + 2GIS firm",
    ),
    entry(
        "usadba-trigorskaya-hotel",
        "Усадьба Тригорская",
        "hotel",
        "VILLAGE",
        "ул. Тригорская, 1",
        57.0248,
        28.9045,
        yandex_url="https://2gis.ru/firm/70000001030946214",
        sources=[gis("70000001030946214")],
        existence_status="TWO_GIS_ACTIVE",
        category_status="TWO_GIS_ACTIVE",
        decision="RESTORE",
        decision_reason="2GIS hotel card Trigorskaya 1",
    ),
    entry(
        "dom-klassika-pushkinskaya-47",
        "Дом Классика",
        "hotel",
        "VILLAGE",
        "ул. Пушкинская, 47",
        57.0245,
        28.9160,
        yandex_url="https://2gis.ru/firm/70000001075366027",
        sources=[gis("70000001075366027")],
        existence_status="TWO_GIS_ACTIVE",
        category_status="TWO_GIS_ACTIVE",
        decision="RESTORE",
        decision_reason="2GIS guest house Pushkinskaya 47",
    ),
    entry(
        "library-pushkinskaya-3",
        "Пушкиногорская центральная районная библиотека",
        "library",
        "VILLAGE",
        "ул. Пушкинская, 3",
        57.0250,
        28.9140,
        opening_hours="Пн–Сб 09:00–18:00",
        yandex_url="https://2gis.ru/firm/70000001046501126",
        sources=[gis("70000001046501126")],
        existence_status="TWO_GIS_ACTIVE",
        category_status="TWO_GIS_ACTIVE",
        hours_status="TWO_GIS_ACTIVE",
        phone_status="UNVERIFIED",
        decision="RESTORE",
        decision_reason="2GIS library card Pushkinskaya 3",
    ),
    entry(
        "art-school-geychenko-pushkinskaya-3",
        "Пушкиногорская школа искусств им. С. С. Гейченко",
        "school",
        "VILLAGE",
        "ул. Пушкинская, 3",
        57.0251,
        28.9142,
        yandex_url="https://yandex.ru/maps/org/pushkinogorskaya_shkola_iskusstv_im_s_s_geychenko/1036116088/",
        yandex_id="1036116088",
        sources=[yandex_org("pushkinogorskaya_shkola_iskusstv_im_s_s_geychenko", "1036116088")],
        existence_status="YANDEX_ACTIVE",
        category_status="YANDEX_ACTIVE",
        decision="RESTORE",
        decision_reason="Yandex org school of arts",
    ),
    entry(
        "prodmag-lermentova-2",
        "Продмаг № 7 РАЙПО, Промтовары № 2",
        "shop",
        "VILLAGE",
        "ул. Лермонтова, 2",
        57.0223571,
        28.9359539,
        phone="+7 (81146) 2-24-34",
        opening_hours="Пн–Вс 08:00–21:00",
        osm_id="osm:prodmag-7",
        sources=[src("OSM", "osm:node/35", entity_id="35", supports=["existence", "name", "address", "coordinates", "phone", "opening_hours"])],
        existence_status="OSM_ACTIVE",
        phone_status="OSM_ACTIVE",
        hours_status="OSM_ACTIVE",
        decision="KEEP",
        decision_reason="Active OSM import on production",
        seed_as_reference=False,
    ),
    entry(
        "velikoluksky-myasokombinat-lermentova",
        "Великолукский мясокомбинат",
        "shop",
        "VILLAGE",
        "ул. Лермонтова",
        57.0265168,
        28.9345111,
        sources=[src("OSM", "osm:node/34", entity_id="34", supports=["existence", "name", "address", "coordinates"])],
        existence_status="OSM_ACTIVE",
        decision="KEEP",
        decision_reason="Active OSM meat shop",
        seed_as_reference=False,
    ),
    entry(
        "azs-pskovnefteprodukt-novorzhevskaya-31",
        "АЗС Псковнефтепродукт",
        "gas",
        "VILLAGE",
        "ул. Новоржевская, 31",
        57.0219,
        28.9399,
        opening_hours="круглосуточно",
        yandex_url="https://yandex.ru/maps/?text=%D0%90%D0%97%D0%A1%20%D0%9D%D0%BE%D0%B2%D0%BE%D1%80%D0%B6%D0%B5%D0%B2%D1%81%D0%BA%D0%B0%D1%8F%2031%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%93%D0%BE%D1%80%D1%8B",
        sources=[
            yandex_search(
                "https://yandex.ru/maps/?text=%D0%90%D0%97%D0%A1%20%D0%9D%D0%BE%D0%B2%D0%BE%D1%80%D0%B6%D0%B5%D0%B2%D1%81%D0%BA%D0%B0%D1%8F%2031%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%93%D0%BE%D1%80%D1%8B"
            )
        ],
        existence_status="YANDEX_ACTIVE",
        hours_status="YANDEX_ACTIVE",
        decision="RESTORE",
        decision_reason="Fuel station Novorzhevskaya 31 — Yandex search; 2GIS not matched",
    ),
    entry(
        "avtoremont-lenina",
        "Авторемонт",
        "auto",
        "VILLAGE",
        "ул. Ленина",
        57.0287699,
        28.9293734,
        phone="+7 (931) 901-56-10",
        opening_hours="Пн–Вс 10:00–21:55",
        sources=[src("OSM", "osm:node/42", entity_id="42", supports=["existence", "name", "address", "coordinates", "phone", "opening_hours"])],
        existence_status="OSM_ACTIVE",
        phone_status="OSM_ACTIVE",
        hours_status="OSM_ACTIVE",
        decision="KEEP",
        decision_reason="Active OSM auto repair",
        seed_as_reference=False,
    ),
    entry(
        "museum-mikhailovskoe-nkc",
        "Государственный музей-заповедник А. С. Пушкина «Михайловское»",
        "culture",
        "VILLAGE",
        "бульвар им. С. С. Гейченко, 1",
        57.0234195,
        28.9307908,
        phone="+7 (81146) 2-23-21",
        website="https://pushkinland.ru",
        yandex_url="https://yandex.ru/maps/?pt=28.9307908,57.0234195&z=17",
        sources=[
            src("OFFICIAL_WEBSITE", "https://pushkinland.ru", supports=["existence", "name", "phone", "address"]),
            src("OFFICIAL_PRIMARY", "https://pushkinland.ru", supports=["existence", "name", "phone"]),
        ],
        existence_status="OFFICIAL_PRIMARY",
        phone_status="OFFICIAL_PRIMARY",
        category_status="OFFICIAL_PRIMARY",
        decision="KEEP",
        decision_reason="Official museum site pushkinland.ru",
        verification_note="Заказ экскурсий: +7 (81146) 2-26-09",
    ),
    entry(
        "monastery-svyatogorsky",
        "Свято-Успенский Святогорский мужской монастырь",
        "culture",
        "VILLAGE",
        "ул. Пушкинская, 1",
        57.0224228,
        28.9200652,
        phone="+7 (81146) 2-33-89",
        website="https://svyatogorskiy-monastery.ru/",
        yandex_url="https://yandex.ru/maps/?pt=28.9200652,57.0224228&z=17",
        sources=[src("OFFICIAL_WEBSITE", "https://svyatogorskiy-monastery.ru/", supports=["existence", "name", "phone", "address"])],
        existence_status="OFFICIAL_PRIMARY",
        phone_status="OFFICIAL_PRIMARY",
        category_status="OFFICIAL_PRIMARY",
        decision="KEEP",
        decision_reason="Official monastery website",
    ),
    entry(
        "hospital-pushkinogorsky-filial",
        'Филиал «Пушкиногорский» ГБУЗ ПО «Островская МБ»',
        "hospital",
        "VILLAGE",
        "ул. Ленина, 41",
        57.0305309,
        28.9328886,
        phone="+7 (81146) 2-27-06",
        website="https://ostrovmb.ru/index/filial_pushkinogorskij/0-63",
        sources=[
            src("OFFICIAL_WEBSITE", "https://ostrovmb.ru/index/filial_pushkinogorskij/0-63", supports=["existence", "name", "address", "phone"]),
            src("GOVERNMENT_REGISTRY", "https://ostrovmb.ru/index/filial_pushkinogorskij/0-63", supports=["existence", "name"]),
        ],
        existence_status="OFFICIAL_PRIMARY",
        phone_status="OFFICIAL_PRIMARY",
        category_status="OFFICIAL_PRIMARY",
        decision="KEEP",
        decision_reason="Official hospital branch page",
        verification_note="Детская консультация: +7 (81146) 2-18-97",
    ),
    entry(
        "administratsiya-lenina-6",
        "Администрация Пушкиногорского муниципального округа",
        "government",
        "VILLAGE",
        "ул. Ленина, 6",
        57.0260,
        28.9110,
        phone="+7 (81146) 2-13-37",
        opening_hours="Пн–Пт 08:00–17:00",
        website="https://pushgory.gosuslugi.ru/",
        sources=[
            src("OFFICIAL_WEBSITE", "https://pushgory.gosuslugi.ru/glavnoe/kontakty/", supports=["existence", "name", "address", "phone", "opening_hours"]),
            src("GOVERNMENT_REGISTRY", "https://pushgory.gosuslugi.ru/", supports=["existence", "name"]),
        ],
        existence_status="OFFICIAL_PRIMARY",
        phone_status="OFFICIAL_PRIMARY",
        hours_status="OFFICIAL_PRIMARY",
        category_status="OFFICIAL_PRIMARY",
        decision="RESTORE",
        decision_reason="Official contacts page Lenina 6",
    ),
    entry(
        "pochta-rossii-lenina-22",
        "Почта России",
        "post",
        "VILLAGE",
        "ул. Ленина, 22",
        57.0266,
        28.9118,
        website="https://www.pochta.ru",
        yandex_url="https://yandex.ru/maps/?text=%D0%9F%D0%BE%D1%87%D1%82%D0%B0%20%D0%9B%D0%B5%D0%BD%D0%B8%D0%BD%D0%B0%2022%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%93%D0%BE%D1%80%D1%8B",
        sources=[
            src("OFFICIAL_WEBSITE", "https://www.pochta.ru", supports=["existence", "name"]),
            yandex_search("https://yandex.ru/maps/?text=%D0%9F%D0%BE%D1%87%D1%82%D0%B0%20%D0%9B%D0%B5%D0%BD%D0%B8%D0%BD%D0%B0%2022%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%93%D0%9E%D1%80%D1%8B"),
        ],
        existence_status="MULTISOURCE_CONFIRMED",
        phone_status="UNVERIFIED",
        decision="RESTORE",
        decision_reason="Post office Lenina 22 — pochta.ru + Yandex",
    ),
    entry(
        "sberbank-atm-lenina-40",
        "Сбербанк (банкомат)",
        "bank",
        "VILLAGE",
        "ул. Ленина, 40",
        57.0264,
        28.9102,
        phone="900",
        opening_hours="ежедневно 06:00–23:00",
        website="https://www.sberbank.ru",
        yandex_url="https://2gis.ru/firm/70000001044502481",
        sources=[
            gis("70000001044502481"),
            src("OFFICIAL_WEBSITE", "https://www.sberbank.ru", supports=["existence", "name"]),
        ],
        existence_status="MULTISOURCE_CONFIRMED",
        category_status="MULTISOURCE_CONFIRMED",
        phone_status="OFFICIAL_PRIMARY",
        hours_status="TWO_GIS_ACTIVE",
        decision="RESTORE",
        decision_reason="2GIS ATM card + Sberbank network",
        verification_note="Телефон 900 — единый номер сети Сбербанка",
    ),
    entry(
        "avtovokzal-novorzhevskaya-30",
        "Автовокзал Пушкинские Горы",
        "transport",
        "VILLAGE",
        "ул. Новоржевская, 30",
        57.0212461,
        28.9350885,
        yandex_url="https://yandex.ru/maps/org/pskovavtotrans_avtostantsiya/1103286656/",
        yandex_id="1103286656",
        osm_id="osm:transport-11",
        sources=[
            yandex_org("pskovavtotrans_avtostantsiya", "1103286656"),
            src("OSM", "osm:node/11", entity_id="11", supports=["existence", "address", "coordinates"]),
        ],
        existence_status="MULTISOURCE_CONFIRMED",
        address_status="MULTISOURCE_CONFIRMED",
        coordinates_status="MULTISOURCE_CONFIRMED",
        phone_status="UNVERIFIED",
        decision="RESTORE",
        decision_reason="Yandex bus station org + OSM point",
    ),
    entry(
        "kafe-pushkin-lenina-3",
        "Кафе «Пушкинъ»",
        "cafe",
        "VILLAGE",
        "пл. Ленина, 3",
        57.0267,
        28.9112,
        yandex_url="https://yandex.ru/maps/?text=%D0%9A%D0%B0%D1%84%D0%B5%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%8A%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%93%D0%BE%D1%80%D1%8B",
        sources=[
            yandex_search(
                "https://yandex.ru/maps/?text=%D0%9A%D0%B0%D1%84%D0%B5%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%8A%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%93%D0%BE%D1%80%D1%8B"
            )
        ],
        existence_status="YANDEX_ACTIVE",
        phone_status="UNVERIFIED",
        decision="RESTORE",
        decision_reason="Separate from Svjatogor — central square cafe",
        conflict_notes="Distinct from Святогоръ ул. Ленина 2",
    ),
    entry(
        "school-1-lenina-30",
        "Средняя школа №1",
        "school",
        "VILLAGE",
        "ул. Ленина, 30",
        57.0255,
        28.9095,
        yandex_url="https://yandex.ru/maps/?text=%D0%A8%D0%BA%D0%BE%D0%BB%D0%B0%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%93%D0%BE%D1%80%D1%8B",
        sources=[yandex_search("https://yandex.ru/maps/?text=%D0%A8%D0%BA%D0%BE%D0%BB%D0%B0%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%93%D0%BE%D1%80%D1%8B")],
        existence_status="YANDEX_ACTIVE",
        phone_status="UNVERIFIED",
        decision="RESTORE",
        decision_reason="Village school — phone not published without official source",
    ),
    entry(
        "nkc-pushkinskie-gory",
        "НКЦ «Пушкинские Горы»",
        "culture",
        "VILLAGE",
        "б-р им. С.С. Гейченко, 1",
        57.0273,
        28.9095,
        phone="+7 (81146) 2-23-21",
        website="https://pushkinland.ru",
        sources=[src("OFFICIAL_WEBSITE", "https://pushkinland.ru", supports=["existence", "name", "phone"])],
        existence_status="OFFICIAL_PRIMARY",
        phone_status="OFFICIAL_PRIMARY",
        decision="RESTORE",
        decision_reason="Museum NKC — pushkinland.ru",
        verification_note="Научно-культурный центр на въезде в посёлок",
    ),
    entry(
        "parking-museum-kassa",
        "Парковка у кассы музея",
        "parking",
        "VILLAGE",
        "бульв. им. С. С. Гейченко, 1",
        57.0233,
        28.9308,
        sources=[src("OFFICIAL_WEBSITE", "https://pushkinland.ru", supports=["existence", "name", "address"])],
        existence_status="OFFICIAL_PRIMARY",
        decision="RESTORE",
        decision_reason="Museum parking — pushkinland visitor info",
        verification_note="Платный пропуск — уточняйте на pushkinland.ru",
    ),
    entry(
        "usadba-mikhailovskoe-selo",
        "Усадьба «Михайловское»",
        "culture",
        "NEARBY_ATTRACTION",
        "с. Михайловское",
        57.0540,
        28.9680,
        phone="+7 (81146) 2-23-21",
        website="https://pushkinland.ru",
        sources=[src("OFFICIAL_WEBSITE", "https://pushkinland.ru", supports=["existence", "name", "phone"])],
        existence_status="OFFICIAL_PRIMARY",
        phone_status="OFFICIAL_PRIMARY",
        decision="RESTORE",
        decision_reason="Estate outside village — nearby attraction",
    ),
    entry(
        "berezka-cafe-mikhailovskoe",
        "Берёзка",
        "cafe",
        "NEARBY_ATTRACTION",
        "Михайловское, 1/2",
        57.0550,
        28.9700,
        yandex_url="https://2gis.ru/firm/70000001044611536",
        sources=[gis("70000001044611536")],
        existence_status="TWO_GIS_ACTIVE",
        category_status="TWO_GIS_ACTIVE",
        decision="RESTORE",
        decision_reason="Cafe near Mikhailovskoe estate — 2GIS",
    ),
    entry(
        "parking-tri-sosen",
        "Парковка «У Трёх Сосен»",
        "parking",
        "NEARBY_ATTRACTION",
        "у с. Михайловское",
        57.0520,
        28.9650,
        sources=[src("OFFICIAL_WEBSITE", "https://pushkinland.ru", supports=["existence", "name"])],
        existence_status="OFFICIAL_PRIMARY",
        decision="RESTORE",
        decision_reason="Museum visitor parking near Mikhailovskoe",
        verification_note="Заезд от д. Воронич и Луговка",
    ),
    entry(
        "fap-blazhi",
        "ФАП д.Блажи",
        "hospital",
        "MUNICIPAL_DISTRICT",
        "деревня Блажи",
        57.0855884,
        28.8787536,
        sources=[src("OSM", "osm:node/27", entity_id="27", supports=["existence", "name", "address", "coordinates"])],
        existence_status="OSM_ACTIVE",
        decision="KEEP",
        decision_reason="Outside village — OSM import retained",
        seed_as_reference=False,
    ),
    entry(
        "fap-krylovo",
        "ФАП д.Крылово",
        "hospital",
        "MUNICIPAL_DISTRICT",
        "деревня Крылово",
        57.0736659,
        29.0064915,
        sources=[src("OSM", "osm:node/28", entity_id="28", supports=["existence", "name", "address", "coordinates"])],
        existence_status="OSM_ACTIVE",
        decision="KEEP",
        seed_as_reference=False,
    ),
]

out = {
    "generated_at": CHECKED,
    "baseline_git": BASELINE_GIT,
    "inventory_passes": 2,
    "places": places,
    "summary": {
        "total_candidates": len(places),
        "village_active": sum(
            1 for p in places if p["scope"] == "VILLAGE" and p["decision"] in ("KEEP", "RESTORE")
        ),
        "nearby_attractions": sum(1 for p in places if p["scope"] == "NEARBY_ATTRACTION"),
        "multisource": sum(1 for p in places if p["existence_status"] == "MULTISOURCE_CONFIRMED"),
        "yandex_only": sum(1 for p in places if p["existence_status"] == "YANDEX_ACTIVE"),
        "two_gis_only": sum(1 for p in places if p["existence_status"] == "TWO_GIS_ACTIVE"),
        "owner_confirmed": sum(1 for p in places if p["existence_status"] == "OWNER_CONFIRMED"),
        "restored": sum(1 for p in places if p["decision"] == "RESTORE"),
    },
}

root = Path(__file__).resolve().parents[1]
for dest in (
    root / "docs" / "factual-integrity" / "stage-02-place-inventory.json",
    root / "backend" / "app" / "data" / "stage-02-place-inventory.json",
):
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {len(places)} places -> {dest}")
