#!/usr/bin/env python3
"""Generate stage-02 place inventory JSON from verified OSINT (2026-06-27)."""
import json
from datetime import datetime, timezone
from pathlib import Path

CHECKED = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

def entry(
    stable_key,
    public_name,
    category,
    scope,
    address,
    lat,
    lng,
    *,
    aliases=None,
    phone=None,
    opening_hours=None,
    website=None,
    social_url=None,
    yandex_url=None,
    yandex_id=None,
    osm_id=None,
    source_types=None,
    existence_status="YANDEX_ACTIVE",
    name_status="YANDEX_ACTIVE",
    address_status="YANDEX_ACTIVE",
    coordinates_status="YANDEX_ACTIVE",
    phone_status="UNVERIFIED",
    hours_status="UNVERIFIED",
    active_status="ACTIVE",
    decision="RESTORE",
    decision_reason="",
    verification_note=None,
    seed_as_reference=True,
    conflict_notes=None,
):
    if phone:
        phone_status = phone_status if phone_status != "UNVERIFIED" else (
            "OWNER_CONFIRMED" if existence_status == "OWNER_CONFIRMED" else
            "OFFICIAL_PRIMARY" if existence_status == "OFFICIAL_PRIMARY" else
            "YANDEX_ACTIVE" if "yandex" in (source_types or []) else
            "OSM_ACTIVE" if "osm" in (source_types or []) else "UNVERIFIED"
        )
    if opening_hours:
        hours_status = hours_status if hours_status != "UNVERIFIED" else (
            "YANDEX_ACTIVE" if "yandex" in (source_types or []) else "UNVERIFIED"
        )
    return {
        "stable_key": stable_key,
        "public_name": public_name,
        "aliases": aliases or [],
        "category": category,
        "scope": scope,
        "address": address,
        "latitude": lat,
        "longitude": lng,
        "phone": phone,
        "opening_hours": opening_hours,
        "website": website,
        "social_url": social_url,
        "yandex_url": yandex_url,
        "yandex_id": yandex_id,
        "osm_id": osm_id,
        "source_types": source_types or [],
        "source_checked_at": CHECKED,
        "existence_status": existence_status,
        "name_status": name_status,
        "address_status": address_status,
        "coordinates_status": coordinates_status,
        "phone_status": phone_status,
        "hours_status": hours_status,
        "active_status": active_status,
        "conflict_notes": conflict_notes,
        "decision": decision,
        "decision_reason": decision_reason,
        "verification_note": verification_note,
        "seed_as_reference": seed_as_reference,
    }


places = [
    entry(
        "shinomontazh-aerodromnaya-23",
        "Шиномонтаж",
        "tyre",
        "VILLAGE",
        "ул. Аэродромная, 23",
        57.0173,
        28.9335,
        aliases=["Шиномонтажная мастерская"],
        phone="+7 (906) 221-03-54",
        opening_hours=None,
        yandex_url="https://yandex.ru/maps/?text=%D1%88%D0%B8%D0%BD%D0%BE%D0%BC%D0%BE%D0%BD%D1%82%D0%B0%D0%B6%20%D0%90%D1%8D%D1%80%D0%BE%D0%B4%D1%80%D0%BE%D0%BC%D0%BD%D0%B0%D1%8F%2023%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%93%D0%BE%D1%80%D1%8B",
        source_types=[
            "https://2gis.ru/firm/70000001075370090",
            "https://pskov.auto2.info/pskov/shinomontazh-155048/",
        ],
        existence_status="OWNER_CONFIRMED",
        phone_status="OWNER_CONFIRMED",
        hours_status="UNVERIFIED",
        decision="RESTORE",
        decision_reason="OWNER_CONFIRMED by project owner; Yandex/2GIS card at Aerodromnaya 23",
        verification_note="Доп. телефон: +7 (981) 783-86-67 (публичный, 2GIS)",
    ),
    entry(
        "pyaterochka-lenina-20a",
        "Пятёрочка",
        "supermarket",
        "VILLAGE",
        "ул. Ленина, 20А",
        57.0264,
        28.9106,
        phone="8-800-555-55-05",
        opening_hours="ежедневно 08:00–23:00",
        website="https://5ka.ru",
        yandex_url="https://yandex.ru/maps/org/pyatyorochka/48515124540/",
        yandex_id="48515124540",
        source_types=["https://yandex.ru/maps/org/pyatyorochka/48515124540/", "https://5ka.ru"],
        existence_status="MULTISOURCE_CONFIRMED",
        decision="RESTORE",
        decision_reason="Yandex active card + chain official site",
    ),
    entry(
        "pyaterochka-pushkinskaya-11",
        "Пятёрочка",
        "supermarket",
        "VILLAGE",
        "ул. Пушкинская, 11",
        57.0259,
        28.9148,
        phone="8-800-555-55-05",
        website="https://5ka.ru",
        yandex_url="https://yandex.ru/maps/org/pyatyorochka/48299237149/",
        yandex_id="48299237149",
        source_types=["https://yandex.ru/maps/org/pyatyorochka/48299237149/"],
        existence_status="YANDEX_ACTIVE",
        decision="RESTORE",
        decision_reason="Second Pyaterochka branch in village — separate address",
    ),
    entry(
        "magnit-lenina-42",
        "Магнит",
        "supermarket",
        "VILLAGE",
        "ул. Ленина, 42",
        57.0261,
        28.9112,
        phone="8-800-200-90-02",
        opening_hours="ежедневно до 22:00",
        website="https://magnit.ru",
        yandex_url="https://yandex.ru/maps/org/magnit/1613176821/",
        yandex_id="1613176821",
        source_types=["https://yandex.ru/maps/org/magnit/1613176821/", "https://magnit.ru"],
        existence_status="MULTISOURCE_CONFIRMED",
        decision="RESTORE",
        decision_reason="Yandex active + Magnit chain site",
    ),
    entry(
        "magnit-novorzhevskaya-25",
        "Магнит",
        "supermarket",
        "VILLAGE",
        "ул. Новоржевская, 25",
        57.0258,
        28.9125,
        phone="8-800-200-90-02",
        opening_hours="ежедневно до 22:00",
        website="https://magnit.ru",
        yandex_url="https://yandex.ru/maps/org/magnit/1624883377/",
        yandex_id="1624883377",
        source_types=["https://yandex.ru/maps/org/magnit/1624883377/"],
        existence_status="YANDEX_ACTIVE",
        decision="RESTORE",
        decision_reason="Separate Magnit branch — Novorzhevskaya 25",
    ),
    entry(
        "m-kosmetik-lenina-42",
        "М.Косметик",
        "beauty",
        "VILLAGE",
        "ул. Ленина, 42",
        57.0261,
        28.9112,
        phone="8-800-200-90-02",
        opening_hours="ежедневно до 22:00",
        website="https://magnit.ru",
        yandex_url="https://yandex.ru/maps/org/magnit/1613176821/",
        source_types=["https://yandex.ru/maps/org/magnit/1613176821/"],
        existence_status="YANDEX_ACTIVE",
        decision="RESTORE",
        decision_reason="Cosmetics shop in Magnit building — same address, different category",
        verification_note="Магазин косметики в здании Магнит",
    ),
    entry(
        "apteka-a-lenina-20a",
        "Аптека-А",
        "pharmacy",
        "VILLAGE",
        "ул. Ленина, 20А",
        57.0263,
        28.9108,
        phone=None,
        opening_hours=None,
        yandex_url="https://yandex.ru/maps/?text=%D0%90%D0%BF%D1%82%D0%B5%D0%BA%D0%B0-%D0%90%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%93%D0%BE%D1%80%D1%8B%20%D0%9B%D0%B5%D0%BD%D0%B8%D0%BD%D0%B0%2020%D0%90",
        source_types=["https://yandex.ru/maps/org/pyatyorochka/48515124540/"],
        existence_status="YANDEX_ACTIVE",
        phone_status="UNVERIFIED",
        hours_status="UNVERIFIED",
        decision="RESTORE",
        decision_reason="Pharmacy in Pyaterochka building per Yandex reviews; local phone not re-verified",
    ),
    entry(
        "apteka-a-novorzhevskaya-25",
        "Аптека-А",
        "pharmacy",
        "VILLAGE",
        "ул. Новоржевская, 25",
        57.0258,
        28.9125,
        phone=None,
        yandex_url="https://yandex.ru/maps/org/magnit/1624883377/",
        source_types=["https://yandex.ru/maps/org/magnit/1624883377/"],
        existence_status="YANDEX_ACTIVE",
        phone_status="UNVERIFIED",
        decision="RESTORE",
        decision_reason="Pharmacy at Magnit Novorzhevskaya per Yandex reviews",
    ),
    entry(
        "raypo-trigorskaya-3",
        "Пушкиногорское РАЙПО",
        "supermarket",
        "VILLAGE",
        "ул. Тригорская, 3",
        57.0249,
        28.9048,
        yandex_url="https://yandex.ru/maps/org/pushkinogorskoye_raypo/11910956685/",
        yandex_id="11910956685",
        source_types=["https://yandex.ru/maps/org/pushkinogorskoye_raypo/11910956685/"],
        existence_status="YANDEX_ACTIVE",
        decision="RESTORE",
        decision_reason="Yandex active cooperative store",
    ),
    entry(
        "prodmag-lermentova-2",
        "Продмаг № 7 РАЙПО, Промтовары № 2",
        "shop",
        "VILLAGE",
        "ул. Лермонтова, 2",
        57.0223571,
        28.9359539,
        phone="+7 (81146) 2-24-34",
        opening_hours="Пн–Вс 08:00–21:00",
        osm_id="osm:prodmag-7",
        source_types=["https://pushkinskie-gory.xyz/api/v1/places (OSM import id=35)"],
        existence_status="OSM_ACTIVE",
        decision="KEEP",
        decision_reason="Active OSM import on production",
        seed_as_reference=False,
    ),
    entry(
        "velikoluksky-myasokombinat-lermentova",
        "Великолукский мясокомбинат",
        "shop",
        "VILLAGE",
        "ул. Лермонтова",
        57.0265168,
        28.9345111,
        source_types=["https://pushkinskie-gory.xyz/api/v1/places (OSM import id=34)"],
        existence_status="OSM_ACTIVE",
        decision="KEEP",
        decision_reason="Active OSM meat shop",
        seed_as_reference=False,
    ),
    entry(
        "azs-pskovnefteprodukt-novorzhevskaya-31",
        "АЗС Псковнефтепродукт",
        "gas",
        "VILLAGE",
        "ул. Новоржевская, 31",
        57.0219,
        28.9399,
        opening_hours="круглосуточно",
        yandex_url="https://yandex.ru/maps/?text=%D0%90%D0%97%D0%A1%20%D0%9D%D0%BE%D0%B2%D0%BE%D1%80%D0%B6%D0%B5%D0%B2%D1%81%D0%BA%D0%B0%D1%8F%2031%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%93%D0%BE%D1%80%D1%8B",
        source_types=["https://yandex.ru/maps/?text=АЗС%20Новоржевская%2031%20Пушкинские%20Горы"],
        existence_status="YANDEX_ACTIVE",
        phone_status="UNVERIFIED",
        decision="RESTORE",
        decision_reason="Fuel station on Novorzhevskaya — Yandex map search",
    ),
    entry(
        "avtoremont-lenina",
        "Авторемонт",
        "auto",
        "VILLAGE",
        "ул. Ленина",
        57.0287699,
        28.9293734,
        phone="+7 (931) 901-56-10",
        opening_hours="Пн–Вс 10:00–21:55",
        source_types=["https://pushkinskie-gory.xyz/api/v1/places (OSM import id=42)"],
        existence_status="OSM_ACTIVE",
        decision="KEEP",
        decision_reason="Active OSM auto repair",
        seed_as_reference=False,
    ),
    entry(
        "museum-mikhailovskoe-nkc",
        "Государственный музей-заповедник А. С. Пушкина «Михайловское»",
        "culture",
        "VILLAGE",
        "бульвар им. С. С. Гейченко, 1",
        57.0234195,
        28.9307908,
        phone="+7 (81146) 2-23-21",
        website="https://pushkinland.ru",
        yandex_url="https://yandex.ru/maps/?pt=28.9307908,57.0234195&z=17",
        source_types=["https://pushkinland.ru", "https://rvb.ru/pushkin/toc.htm"],
        existence_status="OFFICIAL_PRIMARY",
        phone_status="OFFICIAL_PRIMARY",
        hours_status="UNVERIFIED",
        decision="KEEP",
        decision_reason="Official museum site",
        verification_note="Заказ экскурсий: +7 (81146) 2-26-09",
    ),
    entry(
        "monastery-svyatogorsky",
        "Свято-Успенский Святогорский мужской монастырь",
        "culture",
        "VILLAGE",
        "ул. Пушкинская, 1",
        57.0224228,
        28.9200652,
        phone="+7 (81146) 2-33-89",
        website="https://svyatogorskiy-monastery.ru/",
        yandex_url="https://yandex.ru/maps/?pt=28.9200652,57.0224228&z=17",
        source_types=["https://svyatogorskiy-monastery.ru/"],
        existence_status="OFFICIAL_PRIMARY",
        phone_status="OFFICIAL_PRIMARY",
        decision="KEEP",
        decision_reason="Official monastery website",
    ),
    entry(
        "hospital-pushkinogorsky-filial",
        'Филиал «Пушкиногорский» ГБУЗ ПО «Островская МБ»',
        "hospital",
        "VILLAGE",
        "ул. Ленина, 41",
        57.0305309,
        28.9328886,
        phone="+7 (81146) 2-27-06",
        website="https://ostrovmb.ru/index/filial_pushkinogorskij/0-63",
        source_types=["https://ostrovmb.ru/index/filial_pushkinogorskij/0-63"],
        existence_status="OFFICIAL_PRIMARY",
        phone_status="OFFICIAL_PRIMARY",
        decision="KEEP",
        decision_reason="Official hospital branch page",
        verification_note="Детская консультация: +7 (81146) 2-18-97",
    ),
    entry(
        "administratsiya-lenina-6",
        "Администрация Пушкиногорского муниципального округа",
        "government",
        "VILLAGE",
        "ул. Ленина, 6",
        57.0260,
        28.9110,
        phone="+7 (81146) 2-13-37",
        opening_hours="Пн–Пт 08:00–17:00",
        website="https://pushgory.gosuslugi.ru/",
        source_types=["https://pushgory.gosuslugi.ru/glavnoe/kontakty/"],
        existence_status="OFFICIAL_PRIMARY",
        phone_status="OFFICIAL_PRIMARY",
        hours_status="OFFICIAL_PRIMARY",
        decision="RESTORE",
        decision_reason="Official contacts page — corrected address Lenina 6 (not placeholder 2-01-01)",
    ),
    entry(
        "pochta-rossii-lenina-22",
        "Почта России",
        "post",
        "VILLAGE",
        "ул. Ленина, 22",
        57.0266,
        28.9118,
        phone=None,
        website="https://www.pochta.ru",
        yandex_url="https://yandex.ru/maps/?text=%D0%9F%D0%BE%D1%87%D1%82%D0%B0%20%D0%9B%D0%B5%D0%BD%D0%B8%D0%BD%D0%B0%2022%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%93%D0%BE%D1%80%D1%8B",
        source_types=["https://www.pochta.ru", "https://yandex.ru/maps/?text=Почта%20Пушкинские%20Горы"],
        existence_status="MULTISOURCE_CONFIRMED",
        phone_status="UNVERIFIED",
        hours_status="UNVERIFIED",
        decision="RESTORE",
        decision_reason="Post office at Lenina 22 — network site + Yandex",
    ),
    entry(
        "sberbank-atm-lenina-40",
        "Сбербанк (банкомат)",
        "bank",
        "VILLAGE",
        "ул. Ленина, 40",
        57.0264,
        28.9102,
        phone="900",
        opening_hours="круглосуточно",
        website="https://www.sberbank.ru",
        source_types=["https://www.sberbank.ru"],
        existence_status="OFFICIAL_PRIMARY",
        decision="RESTORE",
        decision_reason="Sberbank network ATM — hotline 900, not a local branch phone",
        verification_note="Телефон 900 — единый номер сети Сбербанка",
    ),
    entry(
        "avtovokzal-novorzhevskaya-30",
        "Автовокзал Пушкинские Горы",
        "transport",
        "VILLAGE",
        "ул. Новоржевская, 30",
        57.0212461,
        28.9350885,
        phone=None,
        yandex_url="https://yandex.ru/maps/?text=%D0%90%D0%B2%D1%82%D0%BE%D0%B2%D0%BE%D0%BA%D0%B7%D0%B0%D0%BB%20%D0%9D%D0%BE%D0%B2%D0%BE%D1%80%D0%B6%D0%B5%D0%B2%D1%81%D0%BA%D0%B0%D1%8F%2030",
        osm_id="osm:transport-11",
        source_types=["https://pushkinskie-gory.xyz/api/v1/places (OSM id=11)"],
        existence_status="OSM_ACTIVE",
        phone_status="UNVERIFIED",
        hours_status="UNVERIFIED",
        decision="RESTORE",
        decision_reason="Bus station OSM point at Novorzhevskaya 30 — placeholder phone removed",
        seed_as_reference=True,
    ),
    entry(
        "kafe-pushkin-lenina-3",
        "Кафе «Пушкинъ»",
        "cafe",
        "VILLAGE",
        "пл. Ленина, 3",
        57.0267,
        28.9112,
        phone=None,
        opening_hours=None,
        yandex_url="https://yandex.ru/maps/?text=%D0%9A%D0%B0%D1%84%D0%B5%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%8A%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%93%D0%BE%D1%80%D1%8B",
        source_types=["https://yandex.ru/maps/?text=Кафе%20Пушкинъ%20Пушкинские%20Горы"],
        existence_status="YANDEX_ACTIVE",
        phone_status="UNVERIFIED",
        hours_status="UNVERIFIED",
        decision="RESTORE",
        decision_reason="Cafe on central square — Yandex; old phone 2-14-00 not re-verified",
    ),
    entry(
        "school-1-lenina-30",
        "Средняя школа №1",
        "school",
        "VILLAGE",
        "ул. Ленина, 30",
        57.0255,
        28.9095,
        phone=None,
        opening_hours=None,
        yandex_url="https://yandex.ru/maps/?text=%D0%A8%D0%BA%D0%BE%D0%BB%D0%B0%20%D0%9F%D1%83%D1%88%D0%BA%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B5%20%D0%93%D0%BE%D1%80%D1%8B",
        source_types=["https://yandex.ru/maps/?text=Школа%20Пушкинские%20Горы"],
        existence_status="YANDEX_ACTIVE",
        phone_status="UNVERIFIED",
        decision="RESTORE",
        decision_reason="Village school — phone not published without official source",
    ),
    entry(
        "nkc-pushkinskie-gory",
        "НКЦ «Пушкинские Горы»",
        "culture",
        "VILLAGE",
        "б-р им. С.С. Гейченко, 1",
        57.0273,
        28.9095,
        phone="+7 (81146) 2-23-21",
        website="https://pushkinland.ru",
        source_types=["https://pushkinland.ru"],
        existence_status="OFFICIAL_PRIMARY",
        decision="RESTORE",
        decision_reason="Museum scientific-cultural center — pushkinland.ru",
        verification_note="Научно-культурный центр на въезде в посёлок",
    ),
    entry(
        "parking-museum-kassa",
        "Парковка у кассы музея",
        "parking",
        "VILLAGE",
        "бульв. им. С. С. Гейченко, 1",
        57.0233,
        28.9308,
        opening_hours=None,
        source_types=["https://pushkinland.ru"],
        existence_status="OFFICIAL_PRIMARY",
        decision="RESTORE",
        decision_reason="Museum parking — pushkinland visitor info",
        verification_note="Платный пропуск — уточняйте на pushkinland.ru",
    ),
    entry(
        "usadba-mikhailovskoe-selo",
        "Усадьба «Михайловское»",
        "culture",
        "NEARBY_ATTRACTION",
        "с. Михайловское",
        57.0540,
        28.9680,
        phone="+7 (81146) 2-23-21",
        website="https://pushkinland.ru",
        source_types=["https://pushkinland.ru"],
        existence_status="OFFICIAL_PRIMARY",
        decision="RESTORE",
        decision_reason="Estate outside village center — nearby attraction",
    ),
    entry(
        "parking-tri-sosen",
        "Парковка «У Трёх Сосен»",
        "parking",
        "NEARBY_ATTRACTION",
        "у с. Михайловское",
        57.0520,
        28.9650,
        source_types=["https://pushkinland.ru"],
        existence_status="OFFICIAL_PRIMARY",
        decision="RESTORE",
        decision_reason="Museum visitor parking near Mikhailovskoe estate",
        verification_note="Заезд от д. Воронич и Луговка",
    ),
    entry(
        "fap-blazhi",
        "ФАП д.Блажи",
        "hospital",
        "MUNICIPAL_DISTRICT",
        "деревня Блажи",
        57.0855884,
        28.8787536,
        source_types=["https://pushkinskie-gory.xyz/api/v1/places (OSM id=27)"],
        existence_status="OSM_ACTIVE",
        decision="KEEP",
        decision_reason="Outside village — kept as OSM import, not counted as village org",
        seed_as_reference=False,
    ),
    entry(
        "fap-krylovo",
        "ФАП д.Крылово",
        "hospital",
        "MUNICIPAL_DISTRICT",
        "деревня Крылово",
        57.0736659,
        29.0064915,
        source_types=["https://pushkinskie-gory.xyz/api/v1/places (OSM id=28)"],
        existence_status="OSM_ACTIVE",
        decision="KEEP",
        seed_as_reference=False,
    ),
]

out = {
    "generated_at": CHECKED,
    "baseline_git": "2a2052184eedc8ed6a359ffa4e1b48382bb228bf",
    "inventory_passes": 2,
    "places": places,
    "summary": {
        "total_candidates": len(places),
        "village_active": sum(1 for p in places if p["scope"] == "VILLAGE" and p["decision"] in ("KEEP", "RESTORE")),
        "nearby_attractions": sum(1 for p in places if p["scope"] == "NEARBY_ATTRACTION"),
        "restored": sum(1 for p in places if p["decision"] == "RESTORE"),
    },
}

dest = Path(__file__).resolve().parents[1] / "docs" / "factual-integrity" / "stage-02-place-inventory.json"
dest.parent.mkdir(parents=True, exist_ok=True)
dest.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"Wrote {len(places)} places to {dest}")
