"""Territorial scope labels for place directory entries."""

VILLAGE = "VILLAGE"
NEARBY_ATTRACTION = "NEARBY_ATTRACTION"
MUNICIPAL_DISTRICT = "MUNICIPAL_DISTRICT"

ALL_SCOPES = frozenset({VILLAGE, NEARBY_ATTRACTION, MUNICIPAL_DISTRICT})
